=== FateOfWind/Proyecto-HTML-Bloodborne/dtd/DLC.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- DTD generado con XMLSpy v2020 rel. 2 (x64) (http://www.altova.com) -->
<!ELEMENT DLC (Mas_contenido+)>
<!ELEMENT Fecha (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT publisher (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT Mas_contenido ((nombre, precio, Fecha, titulo, descripcion, publisher) | (titulo, descripcion))>

=== FateOfWind/Proyecto-HTML-Bloodborne/xml/DLC.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE DLC SYSTEM "C:\Users\torre\OneDrive\Escritorio\Proyecto HTML Bloodborne - Sergio Torres\dtd\DLC.dtd">
<?xml-stylesheet type="text/xsl" href="..\xslt\DLC.xslt"?>
<DLC>
	<Mas_contenido>
		<nombre>Bloodborne The Old Hunters</nombre>
		<precio>20$</precio>
		<Fecha>24 de noviembre</Fecha>
		<titulo>Descucbre el pasado de Yharnam</titulo>
		<descripcion>Experimenta la pesadilla de los cazadores que alguna vez guardaron los secretos más profundos y oscuros de Byrgenwerth, y descubre los misterios del siniestro pasado de Yharnam en la expansión de código de contenido descargable (DLC) de The Old Hunters para Bloodborne™. Viaja a un mundo donde los cazadores del pasado han quedado atrapados hasta la eternidad, descubre cantidades de trajes y armas nuevas para agregar a tu arsenal, y explora nuevos escenarios llenos de peligros, recompensas y bestias mortales para cazar.</descripcion>
		<publisher>Sony entertaiment</publisher>
	</Mas_contenido>
	<Mas_contenido>
		<titulo>Mas cazadores</titulo>
		<descripcion>Únete a una gran variedad de cazadores nuevos, algunos provenientes del Lejano Oriente. ¿Qué horrores habrán visto, atrapados en esta pesadilla eterna?</descripcion>
	</Mas_contenido>
	<Mas_contenido>
		<titulo>Nuevos enemigos</titulo>
		<descripcion>Al quedar atrapados en este mundo de pesadillas, algunos cazadores perdieron el juicio. Incapaces de distinguir bestias de amigos, vagan sin rumbo y matan todo lo que se atraviesa en su camino. Ten cuidado, porque siguen esgrimiendo sus mortales armas de caza.</descripcion>
	</Mas_contenido>
	<Mas_contenido>
		<titulo>Descubre mas Bosses : Ludwig La bestia terrorifica</titulo>
		<descripcion>Cuando más virtuoso es el hombre, más maligna es la bestia que esconde en su interior. Es lo que ha sucedido con quien alguna vez fuera un héroe de renombre.

Ahora, se arrastra sin rumbo por las profundidades inundadas de sangre como algo que apenas merece ser llamado bestia.

 </descripcion>
	</Mas_contenido>
	<Mas_contenido>
		<titulo>Nuevas armas :La espada-arco de Simon</titulo>
		<descripcion>A uno de los viejos cazadores no le gustaban las armas de fuego. Este arco especial transformable fue creado especialmente para él.

Pero, ya sabes lo que dicen. Enfrentarse a una bestia solo con un arco es...</descripcion>
	</Mas_contenido>
</DLC>
